services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: myadmin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    networks:
      - keycloak-postgres-network
    command: "start-dev"

networks:
  keycloak-postgres-network:
    external: true

